version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_APIURL: http://localhost:8085
    container_name: frontend-frontend-react
    ports:
      - "4200:80"
    networks:
      - united-net

networks:
  united-net:
    driver: bridge

    # GET para entrar al Proyecto de React:
    # http://localhost:4200