version: "3.9"

services:
  backend:
    image: juanhilares/spring-webflux-backend
    container_name: backend-app
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
      SERVER_URL: http://backend:8085
      RAPIDAPI_DISNEY_URL: https://disney-plus-top-movies-and-tv-shows-api-by-apirobots.p.rapidapi.com
      RAPIDAPI_DISNEY_HOST: disney-plus-top-movies-and-tv-shows-api-by-apirobots.p.rapidapi.com
      RAPIDAPI_DISNEY_APIKEY: bb521ce91fmshe13b754d1467e9fp1bb8a7jsn252d1f31595d
      RAPIDAPI_NETFLIX_URL: https://netflix54.p.rapidapi.com
      RAPIDAPI_NETFLIX_HOST: netflix54.p.rapidapi.com
      RAPIDAPI_NETFLIX_APIKEY: bb521ce91fmshe13b754d1467e9fp1bb8a7jsn252d1f31595d
      SPRING_MONGODB_URI: mongodb+srv://juanhilares:12345@cluster0.v0uij.mongodb.net/RapiAPI
    networks:
      - united-net

  frontend:
    image: juanhilares/frontend-react
    container_name: frontend-app
    environment:
      REACT_APP_APIURL: kkolkk
    ports:
      - "4200:80"
    networks:
      - united-net
    depends_on:
      - backend

networks:
  united-net:
    driver: bridge