apiVersion: apps/v1
kind: Deployment
metadata:
  name: juan-hilares-backend-deployment
  labels:
    app: juan-hilares-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juan-hilares-backend
  template:
    metadata:
      labels:
        app: juan-hilares-backend
    spec:
      containers:
        - name: backend
          image: juanhilares/backend-spring-test
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

          # ------------------------------
          # Readiness Probe
          # ------------------------------
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5

          # ------------------------------
          # Liveness Probe
          # ------------------------------
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          env:
          # -------- ConfigMap --------
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SERVER_URL

            - name: RAPIDAPI_DISNEY_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RAPIDAPI_DISNEY_URL

            - name: RAPIDAPI_DISNEY_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RAPIDAPI_DISNEY_HOST

            - name: RAPIDAPI_NETFLIX_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RAPIDAPI_NETFLIX_URL

            - name: RAPIDAPI_NETFLIX_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RAPIDAPI_NETFLIX_HOST

            # -------- Secret --------
            - name: RAPIDAPI_DISNEY_APIKEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: RAPIDAPI_DISNEY_APIKEY

            - name: RAPIDAPI_NETFLIX_APIKEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: RAPIDAPI_NETFLIX_APIKEY

            - name: SPRING_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SPRING_MONGODB_URI

        - name: sidecar
          image: busybox
          command: ["sh", "-c", "sleep infinity"]