apiVersion: apps/v1
kind: Deployment
metadata:
  name: juan-hilares-frontend-deployment
  labels:
    app: juan-hilares-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juan-hilares-frontend
  template:
    metadata:
      labels:
        app: juan-hilares-frontend
    spec:
      containers:
        - name: frontend
          image: juanjosehilares/front-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_APIURL
              value: "http://127.0.0.1:59733"
