apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: juan-hilares-hackatoon
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXJvdWdoLWRyZWFtLWE1amd2MDF1LXBvb2xlci51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9zcWw/c3NsbW9kZT1yZXF1aXJl
  DATABASE_USERNAME: ZGJfb3duZXI=
  DATABASE_PASSWORD: Q1R0cVhpNkcyTkZ4
  RAPIDAPI_URL: aHR0cHM6Ly9hZ2UtZGV0ZWN0b3IucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_HOST: YWdlLWRldGVjdG9yLnAucmFwaWRhcGkuY29t